# Dockerfile para o frontend Next.js
FROM node:18

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos package.json e package-lock.json
COPY client/package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código
COPY client/ .

# # Construa o projeto
# RUN npm run build

# Exponha a porta usada pelo Next.js
EXPOSE 3000

# Inicie o servidor Next.js
CMD ["npm", "run", "dev"]
