services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: projectfullstack_client
    container_name: projectfullstack_client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3333

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: projectfullstack_server
    container_name: projectfullstack_server
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    command: >
      sh -c "npx prisma migrate deploy && npm run start"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: projectfullstack_db
    container_name: projectfullstack_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projectfullstackdb
