# Use a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Configure variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=projectfullstackdb
